name: Go Design Patterns
author:
  name: Alex Lockwood
  googleplus: https://google.com/+AlexLockwood
  twitter: https://twitter.com/alexjlockwood
  stackoverflow: http://stackoverflow.com/users/844882
  flickr: http://www.flickr.com/photos/tailorransom
  github: https://github.com/alexjlockwood
  feedburner: http://feeds.feedburner.com/godesignpatterns

baseurl: http://www.godesignpatterns.com
description: 'Description'

paginate: 4
excerpt_separator: <!--more-->

pygments: true
markdown: redcarpet

relative_permalinks: false
permalink: /:year/:month/:title.html

exclude: ['README.md', 'LICENSE.txt']
