name: Go Design Patterns
author:
  name: Alex Lockwood
  googleplus: https://google.com/+AlexLockwood
  twitter: https://twitter.com/alexjlockwood
  stackoverflow: http://stackoverflow.com/users/844882
  flickr: http://www.flickr.com/photos/tailorransom
  github: https://github.com/alexjlockwood
  feedburner: http://feeds.feedburner.com/godesignpatterns

baseurl: http://www.godesignpatterns.com
description: 'Go Design Patterns is a website for developers who wish to better understand the Go programming language. The tutorials here emphasize proper code design and project maintainability.'

paginate: 5
excerpt_separator: <!--more-->

pygments: true
markdown: redcarpet

relative_permalinks: false
permalink: /:year/:month/:title.html

exclude: ['README.md', 'LICENSE.txt', 'sitemap.xml']

gems:
  - jekyll-sitemap
